### ISSUE TITLE
Staging machine - usr/local/lib is not in LD_LIBRARY_PATH 

### ISSUE THREAD

**Issue by jpablomch** [jblakley/ScannerEKSQS#37]
/usr/local/lib is missing in LD_LIBRARY_PATH

Some shared libraries couldn't be found. This seems to be a problem with all third-party libraries. Below are some errors when running smoke test. 

********* 
Storehouse

Traceback (most recent call last):
  File "smoketest-v3.py", line 14, in <module>
    import scannerpy as scan
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/__init__.py", line 4, in <module>
    from scannerpy.client import Client, start_master, start_worker, CacheMode
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/client.py", line 31, in <module>
    from scannerpy.config import Config
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/config.py", line 8, in <module>
    import storehouse as sh
  File "/usr/local/lib/python3.5/dist-packages/storehouse/__init__.py", line 2, in <module>
    from storehouse._python import *
ImportError: libstorehouse.so: cannot open shared object file: No such file or directory

*********
Hwang 

Traceback (most recent call last):
  File "smoketest-v3.py", line 14, in <module>
    import scannerpy as scan
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/__init__.py", line 4, in <module>
    from scannerpy.client import Client, start_master, start_worker, CacheMode
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/client.py", line 37, in <module>
    from scannerpy.table import Table
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/table.py", line 8, in <module>
    from scannerpy.column import Column
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/column.py", line 15, in <module>
    from scannerpy.storage import NamedVideoStream, NamedStream, NullElement
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/storage.py", line 4, in <module>
    import hwang
  File "/usr/local/lib/python3.5/dist-packages/hwang/__init__.py", line 1, in <module>
    from .video_index import *
  File "/usr/local/lib/python3.5/dist-packages/hwang/video_index.py", line 1, in <module>
    from ._python import *
ImportError: libhwang.so: cannot open shared object file: No such file or directory

**************
ffmpeg 

ffmpeg: error while loading shared libraries: libavdevice.so.57: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "smoketest-v3.py", line 111, in <module>
    output_stream.save_mp4('resized-video')
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/storage.py", line 367, in save_mp4
    return self._sc.sequence(self._name).save_mp4(output_name, fps=fps, scale=scale)
  File "/usr/local/lib/python3.5/dist-packages/scannerpy/column.py", line 334, in save_mp4
    raise ScannerException('ffmpeg failed during mp4 export!')
scannerpy.common.ScannerException: ffmpeg failed during mp4 export!

Solution: Add /usr/local/lib to LD_LIBRARY_PATH in build staging machine script. Check deps.sh.

**Comment by jpablomch** [comment]
Closing. LD_LIBRARY_PATH is exported in setEKSSenv.sh
